Added openpyn installation

diff --git a/functions/install_functions b/functions/install_functions
--- a/functions/install_functions
+++ b/functions/install_functions
@@ -214,3 +214,67 @@ function install_snap_package() {
 		${3}
 	fi
 }
+
+
+# Install pip package
+#
+# ${1} = Name
+# ${2} = package
+# ${3} = return_function
+
+function install_pip_package() {
+	# echo_message header "Starting 'install_package' function..."
+	# If package is not installed
+	# if [ $(check_package_installed ${2}) != 0 ]; then
+	#	echo_message info "${2} is not installed. Installing..."
+		# Install
+			echo_message info "Installing package '${2}'..."
+			# Admin privileges
+			$(pip install ${2})
+			# Finished
+			echo_message success "Installation of package '${2}' is complete."
+			# return
+			${3}
+#	else
+		# Already installed
+#		echo_message info "Package '${2}' is already installed."
+#		whiptail --title "Finished" --msgbox "Installation of ${1} is already complete." 8 56
+		# return
+		${3}
+	#fi
+}
+
+
+# Install from list function
+#
+# ${1} = Name
+# ${2} = list-name
+# ${3} = return_function
+
+function install_pip_from_list() {
+	# echo_message header "Starting 'install_from_list' function..."
+	echo_message title "Starting installation of ${1}..."
+	# Variables
+	LIST=$(dirname "$0")'/data/'${2}'.list'
+	# Draw window
+	# Install loop
+		while IFS= read -r PACKAGE
+		do
+			# If package is not installed
+			if [[ $(check_pip_package_installed $PACKAGE) != 0 ]]; then
+				# Install package
+				echo_message warning "Package '$PACKAGE' is not installed. Installing..."
+				# Admin privileges
+				install_pip_package "$(echo $PACKAGE | cut -d' ' -f1)" "$PACKAGE"
+				# Check if failed
+				if [[ $? != 0 ]]; then
+					echo_message error "Error installing '$PACKAGE'."
+				fi
+		else
+				# Show already installed message
+			echo_message info "Package '$PACKAGE' is installed."
+		fi
+		done < "$LIST"
+		${3}
+}
+
